spring.application.name=FLY_AWAY
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mi_super_secreto_super_seguro_y_largo_de_32_caracteres_o_mas
jwt.expiration-access=86400000 
jwt.expiration-refresh=604800000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=edinson.vasquez@utec.edu.pe
spring.mail.password=Java-smtp-Dagerecticos

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always